import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,validState} from '../src/engine.js';
import {SaveStore,SAVE_KEY} from '../src/storage.js';
import {MAPS,WORLD,WEAPONS,GUN,UPGRADES,BUILD_TYPES,circleRect,segmentCircle,segmentRect} from '../src/data.js';
function memory(){const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
function game(map='yard'){const g=Game.create(map,'normal',1234);g.s.countdown=0;g.s.remaining=0;g.drain();return g;}
function enemy(g,kind='walker',x=g.s.player.x+130,y=g.s.player.y){g.spawn(kind);const e=g.s.enemies.at(-1);e.x=x;e.y=y;return e;}
function tick(g,n=60,input={}){for(let i=0;i<n;i++){g.tick(1/60,input);g.drain();}}
test('geometry: swept shots hit targets and stop at walls',()=>{assert.ok(segmentCircle(0,0,100,0,50,0,10)<.5);assert.equal(segmentCircle(0,0,100,0,50,30,10),Infinity);assert.equal(segmentRect(0,0,100,0,[40,-10,20,20]),.4);});
test('all map and difficulty starts are valid',()=>{for(const m of MAPS)for(const d of ['casual','normal','nightmare']){const g=Game.create(m.id,d,55);assert.ok(validState(g.snapshot()),`${m.id}/${d}`);assert.ok(!m.walls.some(w=>circleRect(g.s.player.x,g.s.player.y,15,w)));}});
test('negative spawn timer is a valid mid-wave save',()=>{const g=game();enemy(g);tick(g,90);assert.ok(g.s.spawnTimer<0);assert.ok(validState(g.snapshot()));});
test('corrupt, dead, and nonfinite saves are rejected',()=>{let s=game().snapshot();s.phase='dead';assert.equal(validState(s),false);s=game().snapshot();s.player.hp=NaN;assert.equal(validState(s),false);s=game().snapshot();s.owned=['unknown'];assert.equal(validState(s),false);});
test('pistol fires without consuming ammunition',()=>{const g=game();enemy(g);tick(g,120,{fire:true,aim:0});assert.ok(g.s.kills>0);assert.equal(g.s.ammo.pistol,-1);});
test('empty weapons fall back to pistol',()=>{const g=game();g.s.owned.push('smg');g.s.ammo.smg=0;g.equip('smg');g.s.player.fire=0;g.shoot(0);assert.equal(g.s.weapon,'pistol');});
test('shop is unavailable in combat and rejects insufficient funds',()=>{const g=game();g.s.cash=99999;assert.equal(g.buy('weapon','smg'),false);g.s.phase='shop';g.s.cash=0;assert.equal(g.buy('weapon','smg'),false);});
test('all weapons can be purchased, equipped, and fired',()=>{for(const w of WEAPONS){const g=game();g.s.phase='shop';g.s.cash=100000;if(w.id!=='pistol')assert.ok(g.buy('weapon',w.id));g.equip(w.id);g.s.phase='active';g.s.player.fire=0;g.s.player.hurt=0;enemy(g,'brute',g.s.player.x+100,g.s.player.y);g.shoot(0);tick(g,100,{fire:true,aim:0});assert.ok(g.s.kills>0||g.s.enemies[0]?.hp<g.s.enemies[0]?.maxHp,w.id);}});
test('upgrade caps and health changes are enforced',()=>{const g=game();g.s.phase='shop';g.s.cash=1e7;for(const u of UPGRADES){for(let n=0;n<u.max;n++)assert.ok(g.buy('upgrade',u.id));assert.equal(g.buy('upgrade',u.id),false);}assert.equal(g.s.player.maxHp,270);assert.equal(g.s.player.hp,270);assert.ok(validState(g.snapshot()));});
test('full heals and full ammo cannot waste credits',()=>{const g=game();g.s.phase='shop';g.s.cash=500;assert.equal(g.buy('supply','heal'),false);assert.equal(g.buy('supply','ammo'),false);assert.equal(g.s.cash,500);});
test('grenade counts and cooldowns are enforced',()=>{const g=game();assert.ok(g.grenade());assert.equal(g.s.grenades,2);assert.equal(g.grenade(),false);assert.equal(g.s.projectiles.length,1);});
test('barrels chain-react and kill nearby enemies',()=>{const g=game();g.s.player.x=1000;g.s.player.y=950;g.s.player.angle=0;assert.ok(g.place());const d=g.s.defenses[0];g.s.defenses.push({...d,id:999,x:d.x+70});enemy(g,'walker',d.x+110,d.y);g.damageDefense(d,100);assert.equal(g.s.defenses.filter(d=>d.hp>0).length,0);assert.ok(g.s.kills>=1);});
test('all defenses place and consume one inventory item',()=>{for(const kind of BUILD_TYPES){const g=game();g.s.build=kind;g.s.inventory[kind]=2;assert.ok(g.place(),kind);assert.equal(g.s.inventory[kind],1);assert.equal(g.s.defenses[0].kind,kind);}});
test('own blasts can hurt, cover shields, mines spare player',()=>{const g=game();g.s.player.hurt=0;g.explode(g.s.player.x,g.s.player.y,100,100,'player');assert.ok(g.s.player.hp<120);g.s.player.hp=120;g.s.player.hurt=0;g.explode(g.s.player.x,g.s.player.y,100,100,'mine');assert.equal(g.s.player.hp,120);});
test('clearing a wave opens shop and grants clear bonus',()=>{const g=game();const e=enemy(g);g.damageEnemy(e,1000);g.tick(1/60);assert.equal(g.s.phase,'shop');assert.equal(g.s.cash,94);assert.ok(validState(g.snapshot()));});
test('warden arrives every fifth wave',()=>{const g=game();g.s.wave=4;g.nextWave();g.s.countdown=0;tick(g,14);assert.ok(g.s.enemies.some(e=>e.kind==='boss'));});
test('save round trip preserves combat, ammo, inventory, and RNG',()=>{const g=game();enemy(g);g.grenade();g.place();tick(g,3);const store=new SaveStore(memory());assert.ok(store.start(g));const data=store.claim();assert.deepEqual(data,g.snapshot());const restored=new Game(data);assert.equal(restored.random(),g.random());});
test('death removes the single live save but keeps high score',()=>{const g=game();const mem=memory(),store=new SaveStore(mem);store.start(g);store.record(1234,2,15);g.s.player.hurt=0;g.damagePlayer(9999);store.write(g);assert.equal(mem.getItem(SAVE_KEY),null);assert.equal(store.record().score,1234);assert.equal(g.s.phase,'dead');});
test('new run replaces old run and prevents old-window resurrection',()=>{const mem=memory(),a=new SaveStore(mem),b=new SaveStore(mem),g=game();a.start(g);const g2=Game.create('bunker','casual',999);b.start(g2);assert.equal(a.write(g),false);assert.equal(a.conflict,true);assert.equal(b.read().data.id,g2.s.id);});
test('taking over a saved run prevents the former tab from writing or deleting it',()=>{const mem=memory(),a=new SaveStore(mem),b=new SaveStore(mem),g=game();a.start(g);b.claim();assert.equal(a.write(g),false);assert.equal(a.clear(g.s.id),false);assert.ok(b.read());});
test('storage failure is reported without crashing gameplay',()=>{const broken={getItem:()=>null,setItem:()=>{throw Error('quota')},removeItem:()=>{throw Error('blocked')}};const s=new SaveStore(broken);assert.equal(s.start(game()),false);assert.match(s.error,/unavailable/);});
test('all enemies can navigate each arena toward a stationary survivor',()=>{for(const m of MAPS){const g=game(m.id);g.s.wave=10;g.s.player.hurt=1e6;for(let i=0;i<16;i++){const kind=i%5===0?'boss':i%3===0?'brute':'walker';const e=enemy(g,kind,35,35);const side=i%4,t=120+Math.floor(i/4)*200;if(side===0){e.x=t+200;e.y=45;}if(side===1){e.x=WORLD.w-45;e.y=t;}if(side===2){e.x=t+200;e.y=WORLD.h-45;}if(side===3){e.x=45;e.y=t;}}tick(g,60*100);const stuck=g.s.enemies.filter(e=>Math.hypot(e.x-g.s.player.x,e.y-g.s.player.y)>135);assert.equal(stuck.length,0,`${m.id}: ${stuck.map(e=>`${e.kind} ${e.x|0},${e.y|0}`).join(';')}`);}});
