import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,validState,circleRect,rayBox} from '../engine.js';
import {MAPS,WEAPONS,UPGRADES,ammoMax} from '../data.js';
import {RunStore} from '../storage.js';
const fresh=(options={})=>new Game({map:'empty',seed:12345,runId:'test-run',...options});
function arena(options={}){const g=fresh(options);g.s.objects=[];g.s.enemies=[];g.s.spawnLeft=0;return g;}
function enemy(g,x=820,y=520,hp=40,type='zombie'){const e={id:g.s.nextId++,type,x,y,hp,maxHp:hp,r:13,speed:43,angle:0,attack:2,stun:0,walk:0};g.s.enemies.push(e);return e;}
class MemoryStorage{constructor(){this.m=new Map();}getItem(k){return this.m.get(k)??null;}setItem(k,v){this.m.set(k,String(v));}removeItem(k){this.m.delete(k);}}

test('every room starts outside cover with a complete valid save',()=>{
 assert.equal(MAPS.length,18);assert.equal(WEAPONS.length,10);
 for(const map of MAPS){const g=fresh({map:map.id});assert.ok(validState(g.snapshot()),map.id);assert.ok(!g.walls.some(w=>circleRect(g.s.player.x,g.s.player.y,14,w)),map.id);assert.ok(g.s.spawnLeft>0);}
});
test('all unblocked room cells connect to the survivor',()=>{for(const map of MAPS){const g=fresh({map:map.id});const disconnected=Array.from(g.flow).filter((d,i)=>d<0&&!g.blocked[i]).length;assert.equal(disconnected,0,map.id);}});
test('seeded room setup and spawn are reproducible',()=>{const a=fresh(),b=fresh();a.spawn();b.spawn();assert.deepEqual(a.snapshot(),b.snapshot());});
test('restoring retains position, enemies, projectiles, upgrades, and RNG',()=>{const g=fresh();for(let i=0;i<210;i++)g.update(1/60,{mx:.4,auto:true});const s=g.snapshot();assert.ok(validState(s));const restored=new Game({},s);assert.deepEqual(restored.snapshot(),s);assert.notEqual(restored.s,s);restored.s.player.x++;assert.notEqual(restored.s.player.x,s.player.x);});
test('pistol consumes no ammo, has cooldown, and kills after two hits',()=>{const g=arena();const e=enemy(g);g.s.player.angle=0;assert.ok(g.shoot());assert.equal(e.hp,16);assert.equal(g.shoot(),false);g.s.player.cool=0;g.shoot();assert.equal(e.hp,0);assert.equal(g.s.kills,1);assert.equal(g.s.ammo.pistol,-1);});
test('empty ammunition switches to the pistol without firing',()=>{const g=arena();g.grant('uzi');g.select('uzi');g.s.ammo.uzi=0;assert.equal(g.shoot(),false);assert.equal(g.s.selected,'pistol');});
test('concrete blocks bullets and the railgun pierces enemies',()=>{const g=arena();g.s.player.angle=0;const a=enemy(g,820),b=enemy(g,900);g.walls=[{x:760,y:480,w:40,h:80}];g.shoot();assert.equal(a.hp,40);g.walls=[];g.grant('rail');g.select('rail');g.s.player.cool=0;g.shoot();assert.equal(a.hp,0);assert.equal(b.hp,0);assert.equal(g.s.kills,2);});
test('axis movement cannot walk through walls or leave the room',()=>{const g=arena();g.walls=[{x:760,y:480,w:40,h:80}];g.move(g.s.player,200,0,14,g.walls);assert.ok(g.s.player.x<=746);g.move(g.s.player,-3000,-3000,14,[]);assert.ok(g.s.player.x>=22&&g.s.player.y>=22);});
test('barrels chain, with splash damage opt-in',()=>{const g=arena();g.s.objects=[{id:20,type:'barrel',x:820,y:520,hp:26,arm:0,damage:160,radius:135},{id:21,type:'barrel',x:920,y:520,hp:26,arm:0,damage:160,radius:135}];const e=enemy(g,1010,520,30);g.explode(815,520,160,135);assert.equal(e.hp,0);assert.equal(g.s.player.hp,100);const h=arena({selfDamage:true});h.explode(725,520,160,135);assert.ok(h.s.player.hp<100);});
test('mines trigger and remote charges wait for detonation',()=>{const g=arena();g.s.objects=[{id:20,type:'mine',x:820,y:520,hp:30,arm:0,damage:180,radius:145}];const e=enemy(g,830,520);g.update(1/60,{});assert.equal(e.hp,0);const h=arena();h.s.objects=[{id:20,type:'charge',x:820,y:520,hp:30,arm:0,damage:250,radius:180}];const q=enemy(h,830,520);h.update(1/60,{});assert.ok(q.hp>0);h.detonate();assert.equal(q.hp,0);});
test('shop guards against overspending, duplicate purchases, and mid-wave purchases',()=>{const g=arena();g.s.cash=10000;assert.equal(g.buyWeapon('uzi'),false);g.s.phase='shop';const before=g.s.cash;assert.ok(g.buyWeapon('uzi'));assert.equal(g.s.cash,before-300);assert.equal(g.buyWeapon('uzi'),false);g.s.cash=0;assert.equal(g.buyWeapon('rail'),false);assert.equal(g.upgrade('damage'),false);assert.equal(g.s.cash,0);});
test('upgrade caps and full-ammunition refills',()=>{const g=arena();g.s.phase='shop';g.s.cash=1000000;g.buyWeapon('uzi');for(const u of UPGRADES){for(let i=0;i<u.max;i++)assert.ok(g.upgrade(u.id));assert.equal(g.upgrade(u.id),false);}assert.equal(g.maxHp,220);g.s.ammo.uzi=0;assert.ok(g.supply('ammo'));assert.equal(g.s.ammo.uzi,ammoMax(WEAPONS[1],g.s.up));assert.equal(g.supply('ammo'),false);});
test('Classic combos unlock weapons; Survival does not auto-grant them',()=>{for(const mode of ['classic','survival']){const g=arena({mode});for(let i=0;i<18;i++)g.hit(enemy(g),100);assert.equal(g.s.bestCombo,18);assert.equal(g.s.owned.includes('uzi'),mode==='classic');assert.equal(g.s.owned.includes('barrel'),mode==='classic');assert.ok(g.s.cash>0);}});
test('cleared waves wait in the shop and the next wave grows',()=>{const g=arena();const total=g.s.total;g.update(1/60,{});assert.equal(g.s.phase,'shop');const cash=g.s.cash;g.update(1,{});assert.equal(g.s.cash,cash);assert.ok(g.nextWave());assert.equal(g.s.wave,2);assert.equal(g.s.phase,'wave');assert.ok(g.s.total>total);});
test('death is terminal and cannot be serialized as a live run',()=>{const g=arena();g.hurt(1000);assert.equal(g.s.phase,'dead');assert.equal(g.s.player.hp,0);assert.equal(validState(g.snapshot()),false);g.update(.05,{auto:true});assert.equal(g.s.phase,'dead');assert.equal(g.shoot(),false);});
test('single slot loads, replaces, and invalidates the old run',()=>{const mem=new MemoryStorage(),s=new RunStore(mem,'unit:');const first=fresh().snapshot();assert.ok(s.start(first));assert.deepEqual(s.load().state,first);const next=fresh({runId:'new-run'}).snapshot();assert.ok(s.start(next));assert.equal(s.load().state.runId,'new-run');assert.equal(s.save(first),false);assert.equal(s.load().state.runId,'new-run');assert.equal([...mem.m.keys()].filter(k=>k.endsWith(':run')).length,1);});
test('death removes the save but keeps records and settings',()=>{const mem=new MemoryStorage(),s=new RunStore(mem,'unit:');const g=fresh();s.start(g.snapshot());s.saveSettings({...s.settings(),sound:false});g.s.score=900;s.record(g.s);s.end(g.s.runId);assert.equal(s.load(),null);assert.equal(mem.getItem(s.key('run')),null);assert.equal(s.save(g.snapshot()),false);assert.equal(s.records().score,900);assert.equal(s.settings().sound,false);});
test('only the active tab may save; expired leases can be resumed',()=>{const mem=new MemoryStorage(),a=new RunStore(mem,'unit:'),b=new RunStore(mem,'unit:');const s=fresh().snapshot();a.start(s);assert.equal(b.acquire(s.runId),false);assert.equal(b.save(s),false);a.release();assert.ok(b.acquire(s.runId));assert.equal(a.save(s),false);assert.ok(b.save(s));mem.setItem(b.key('lease'),JSON.stringify({tab:'old',runId:s.runId,at:Date.now()-10000}));assert.ok(a.acquire(s.runId));});
test('corrupt or foreign saves are refused safely',()=>{const mem=new MemoryStorage(),s=new RunStore(mem,'unit:');s.start(fresh().snapshot());mem.setItem(s.key('run'),'not json');assert.equal(s.load(),null);assert.ok(s.error);for(const mutate of [x=>x.player.hp=-1,x=>x.map='missing',x=>x.version=99,x=>x.owned=['not-a-gun']]){const v=fresh().snapshot();mutate(v);assert.equal(validState(v),false);}});
test('blocked storage warns but still permits an in-memory game',()=>{const blocked={setItem(){throw new Error('blocked');},getItem(){throw new Error('blocked');},removeItem(){throw new Error('blocked');}};const s=new RunStore(blocked,'unit:');assert.equal(s.available,false);assert.ok(s.start(fresh().snapshot()));assert.ok(s.load());s.end('test-run');assert.equal(s.load(),null);});
