import {Game} from './engine.js';
import {SaveStore,SAVE_KEY} from './storage.js';
import {Renderer,miniMap,gunSvg,gearSvg} from './renderer3d.js';
import {AudioFX} from './audio.js';
import {VERSION,MAPS,DIFFICULTIES,WEAPONS,GUN,UPGRADES,SUPPLIES,BUILD_TYPES,UPGRADE_PRICE,clamp} from './data.js';
const $=id=>document.getElementById(id),fmt=n=>Math.floor(n).toLocaleString('en-US'),clock=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
let store;
try{store=new SaveStore(localStorage);}catch{store=new SaveStore({getItem:()=>null,setItem:()=>{throw Error('Storage blocked');},removeItem:()=>{throw Error('Storage blocked');}});}
const settings=store.settings();
let renderer;
try { renderer=new Renderer($('gameCanvas'),settings); }
catch(error) {
  $('boot').innerHTML='<div style="max-width:450px;padding:24px;line-height:1.6">The 3D renderer could not start. This version requires WebGL 2. Close other graphics-heavy tabs, then reload. Your saved run has not been changed.<br><button onclick="location.reload()">Try again</button></div>';
  console.error(error);throw error;
}
const audio=new AudioFX(settings);
let touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!touch){touch=true;document.body.classList.add('is-touch');}},{capture:true,passive:true});
document.body.classList.toggle('is-touch',touch);
if(matchMedia('(prefers-reduced-motion:reduce)').matches)settings.shake=false;
let game=null,paused=true,panelKind='',returnPanel='menu',configReturn='menu',selectedMap='yard',selectedDifficulty='normal',shopTab='weapons',toastTimer=0,last=performance.now(),acc=0,saveClock=0,hudClock=0,lastDock='',deadHandled=false;
let rotationBlocked=false,rotationResume=false,viewportTimer=0;
const keys=new Set(),mouse={x:0,y:0,valid:false,down:false},move={id:null,x:0,y:0},aim={id:null,x:0,y:0};
const attract=Game.create('yard','normal',4001);attract.s.countdown=0;attract.s.player.x=920;attract.s.player.y=490;attract.s.player.hurt=0;attract.s.player.angle=-.6;attract.s.weapon='shotgun';attract.s.owned.push('shotgun');attract.s.ammo.shotgun=75;
for(let i=0;i<27;i++){attract.spawn(i%11===0?'cinder':i%9===0?'brute':'walker');const e=attract.s.enemies.at(-1);e.x=670+(i*197%670);e.y=110+(i*139%770);if(attract.map.walls.some(w=>e.x>w[0]-30&&e.x<w[0]+w[2]+30&&e.y>w[1]-45&&e.y<w[1]+w[3]+25))e.y+=130;e.angle=Math.atan2(490-e.y,920-e.x);e.walk=i;}
attract.s.defenses=[{kind:'barrel',x:870,y:620,r:17,hp:45,maxHp:45,armed:0,fire:0,angle:0},{kind:'barrel',x:1210,y:450,r:17,hp:45,maxHp:45,armed:0,fire:0,angle:0}];
function warning(){const el=$('storageWarning');el.hidden=!store.error;el.textContent=store.error;}
function notice(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3100);}
function resetInput(){keys.clear();mouse.down=false;mouse.valid=false;for(const [o,id] of [[move,'moveStick'],[aim,'aimStick']]){o.id=null;o.x=o.y=0;$(id).style.setProperty('--dx','0px');$(id).style.setProperty('--dy','0px');}}
// Browser lock support varies. The gate is the fallback; combat never runs in portrait.
function requestLandscape(){
  if(!touch)return;
  try{const lock=screen.orientation?.lock;if(typeof lock==='function')Promise.resolve(lock.call(screen.orientation,'landscape')).catch(()=>{});}catch{}
}
function updateViewport(){
  const viewport=window.visualViewport;
  // Safari can report the previous visual viewport during orientation transitions.
  // innerWidth updates first in WebKit; clientWidth and visualViewport may lag a turn.
  const layoutWidth=innerWidth;
  const settled=viewport&&Math.abs(viewport.width-layoutWidth)<4&&Math.abs(viewport.scale-1)<.02;
  const w=Math.round(layoutWidth),h=Math.round(settled?viewport.height:innerHeight);
  if(w<1||h<1)return;
  // Some WebKit mobile views retain the previous CSS viewport after rotation.
  // Re-resolve the meta viewport only on a verified mismatch at normal scale.
  if(touch&&Math.abs(document.documentElement.clientWidth-w)>4&&(!viewport||Math.abs(viewport.scale-1)<.02)){
    const meta=document.querySelector('meta[name="viewport"]');
    const content=`width=${w}, initial-scale=1, viewport-fit=cover`;
    if(meta&&meta.content!==content)meta.content=content;
  }
  document.documentElement.style.setProperty('--viewport-width',w+'px');
  document.documentElement.style.setProperty('--viewport-height',h+'px');
  const blocked=touch&&w<=h,gate=$('orientationGate');
  if(blocked&&!rotationBlocked){
    rotationResume=!!game&&!paused&&game.s.phase!=='dead';rotationBlocked=true;
    resetInput();acc=0;if(rotationResume){paused=true;persist();}
    if(!gate.open)gate.showModal();
  }else if(!blocked){
    const wasBlocked=rotationBlocked;rotationBlocked=false;
    if(gate.open)gate.close();
    renderer.resize();
    if(wasBlocked){last=performance.now();acc=0;if(rotationResume&&game&&!$('panel').open)showPause();rotationResume=false;}
  }
}
function scheduleViewport(){updateViewport();clearTimeout(viewportTimer);viewportTimer=setTimeout(updateViewport,180);}
function focusArena(){const canvas=$('gameCanvas');canvas.tabIndex=-1;canvas.focus({preventScroll:true});}
function closeDialog(){if($('panel').open)$('panel').close();panelKind='';}
function dialog(kind,title,eyebrow,body,foot='',wide=false,extra=''){
  resetInput();panelKind=kind;$('panel').classList.toggle('wide',wide);
  $('panelContent').innerHTML=`<header class="dialog-head"><div><div class="eyebrow-small">${eyebrow}</div><h2 id="panelTitle">${title}</h2></div>${extra}<button class="close" data-action="close" aria-label="Close dialog">×</button></header>${body}<footer class="dialog-foot">${foot}</footer>`;
  if(!$('panel').open)$('panel').showModal();
}
function refreshMenu(){const r=store.read(),best=store.record();$('continueButton').hidden=!r;$('newButton').className=r?'':'primary';$('saveSummary').textContent=r?`Wave ${r.data.wave} · ${MAPS.find(m=>m.id===r.data.map).name} · ${fmt(r.data.cash)} credits. Your run is saved.`:'One automatic save. Death ends the run.';$('recordSummary').textContent=best.score?`BEST ${fmt(best.score)} / WAVE ${best.wave}`:'NO RUNS ON RECORD';warning();}
function toMenu(save=true){if(save&&game&&game.s.phase!=='dead')persist();paused=true;resetInput();game=null;deadHandled=false;closeDialog();$('menu').hidden=false;$('hud').hidden=true;$('controls').hidden=true;refreshMenu();}
function conflict(){paused=true;resetInput();game=null;closeDialog();$('menu').hidden=false;$('hud').hidden=true;$('controls').hidden=true;refreshMenu();notice('This run was opened or cleared in another window. Continue here to take over.');}
function persist(){if(!game||store.conflict)return false;const ok=store.write(game);warning();if(store.conflict){conflict();return false;}$('saveIndicator').textContent=ok?'SAVED':'SAVE UNAVAILABLE';return ok;}
function enter(g,newRun=false){game=g;paused=false;deadHandled=false;lastDock='';last=performance.now();acc=0;saveClock=0;closeDialog();resetInput();$('menu').hidden=true;$('hud').hidden=false;$('controls').hidden=false;if(newRun)store.start(game);game.s.player.hurt=Math.max(game.s.player.hurt,.9);renderer.cx=game.s.player.x;renderer.cy=game.s.player.y;renderer.parts=[];renderer.blasts=[];renderer.texts=[];audio.unlock();warning();hud();if(game.s.phase==='shop')showShop();else{focusArena();if(game.s.phase==='prep')notice('Move, aim, and place defenses. Tap Start wave when ready.');else if(touch)notice('Left thumb moves. Right thumb aims and fires. Manual fire only.');}}
function startNew(){const seed=new Uint32Array(1);try{crypto.getRandomValues(seed);}catch{seed[0]=Date.now();}enter(Game.create(selectedMap,selectedDifficulty,seed[0]),true);processEvents();}
function resumeSaved(){const data=store.claim();if(!data){refreshMenu();notice(store.error||'No saved run. Start a new game.');return;}enter(new Game(data));}
function resume(){if(!game)return;if(renderer.lost){notice('Graphics are recovering. Your run is paused and saved.');return;}if(game.s.phase==='shop'){showShop();return;}closeDialog();resetInput();paused=false;last=performance.now();acc=0;game.s.player.hurt=Math.max(game.s.player.hurt,.5);audio.unlock();focusArena();}
function showPause(){if(!game||game.s.phase==='dead')return;paused=true;resetInput();persist();if(!game)return;dialog('pause','Catch your breath.','RUN PAUSED',`<div class="dialog-body"><p>Wave ${game.s.wave} · ${MAPS.find(m=>m.id===game.s.map).name} · ${clock(game.s.elapsed)} survived</p><div class="pause-actions"><button class="primary" data-action="resume">${game.s.phase==='shop'?'Return to armory':'Resume run'} →</button><button data-action="settings">Settings</button><button data-action="help">Field manual</button><button data-action="menu">Save and return to menu</button><button class="danger" data-action="new">Start a new game</button></div></div>`,`<span>One save slot. Your current run is saved automatically.</span>`);}
function showNew(){const chosen=MAPS.find(m=>m.id===selectedMap);dialog('new','Choose your ground.','NEW RUN',`<div class="dialog-body"><div class="map-grid">${MAPS.map(m=>`<button class="map-card ${m.id===selectedMap?'selected':''}" data-action="map" data-id="${m.id}" aria-pressed="${m.id===selectedMap}"><canvas width="264" height="168" data-map="${m.id}" aria-hidden="true"></canvas><span class="map-info"><strong>${m.name}</strong><small>${m.tag}</small><em>${m.flow}</em></span></button>`).join('')}</div><p class="map-description">${chosen.description}</p><div class="difficulty-row">${Object.entries(DIFFICULTIES).map(([id,d])=>`<button class="${id===selectedDifficulty?'selected':''}" data-action="difficulty" data-id="${id}" aria-pressed="${id===selectedDifficulty}">${d.name}</button>`).join('')}</div><p class="config-note">${chosen.name} flow: <strong>${chosen.flow}</strong>. ${DIFFICULTIES[selectedDifficulty].text} ${touch?'Landscape gives you more room to see the horde.':''}</p></div>`,`<span>${store.read()?'Starting will replace your existing saved run.':'Weapons and upgrades last for this run only.'}</span><button class="primary" data-action="begin">Enter the arena →</button>`,true);document.querySelectorAll('[data-map]').forEach(c=>miniMap(c,MAPS.find(m=>m.id===c.dataset.map),c.dataset.map===selectedMap));}
function confirmNew(){if(!store.read()){startNew();return;}dialog('confirm','Replace this run?','NO GOING BACK',`<div class="dialog-body"><p>Your current run, weapons, and upgrades will be erased when you enter the arena. Your high score stays on record.</p></div>`,`<button data-action="backNew">Keep current run</button><button class="danger" data-action="start">Replace and start</button>`);}
function showShop(){if(!game||game.s.phase!=='shop')return;paused=true;resetInput();persist();if(!game)return;const s=game.s;let cards='';
  if(shopTab==='weapons')cards=WEAPONS.map(w=>{const owned=s.owned.includes(w.id),equipped=s.weapon===w.id;return `<article class="shop-card"><div class="shop-art">${gunSvg(w.id)}</div><div class="shop-card-body"><h3>${w.name}</h3><p>${w.description}</p><span class="chip">${w.ammo===-1?'UNLIMITED AMMO':`${owned?s.ammo[w.id]:w.ammo} / ${w.ammo} ROUNDS`}</span><button class="${owned?'owned':'primary'}" data-action="${owned?'equip':'buy'}" data-kind="weapon" data-id="${w.id}" ${equipped||(!owned&&s.cash<w.price)?'disabled':''}>${equipped?'EQUIPPED':owned?'EQUIP':`${fmt(w.price)} CR · BUY`}</button></div></article>`;}).join('');
  if(shopTab==='upgrades')cards=UPGRADES.map((u,i)=>{const level=s.upgrades[u.id],cost=UPGRADE_PRICE(u,level);return `<article class="shop-card"><div class="shop-art"><span class="upgrade-icon">${['+15%','+10%','+30','−8%','+7%','+45'][i]}</span></div><div class="shop-card-body"><h3>${u.name}</h3><p>${u.description}</p><div class="level-pips" aria-label="Level ${level} of ${u.max}">${Array.from({length:u.max},(_,j)=>`<i class="${j<level?'on':''}"></i>`).join('')}</div><button class="primary" data-action="buy" data-kind="upgrade" data-id="${u.id}" ${level>=u.max||s.cash<cost?'disabled':''}>${level>=u.max?'MAX LEVEL':`${fmt(cost)} CR · UPGRADE`}</button></div></article>`;}).join('');
  if(shopTab==='supplies'||shopTab==='defenses')cards=SUPPLIES.filter(u=>BUILD_TYPES.includes(u.id)===(shopTab==='defenses')).map((u,i)=>{const full=u.id==='heal'?s.player.hp>=s.player.maxHp:u.id==='ammo'?s.owned.every(id=>GUN[id].ammo<0||s.ammo[id]>=GUN[id].ammo):u.id==='grenade'?s.grenades>=99:s.inventory[u.id]>=99;return `<article class="shop-card"><div class="shop-art">${gearSvg(u.id)}</div><div class="shop-card-body"><h3>${u.name}</h3><p>${u.description}</p><span class="chip">${u.id==='heal'?`${Math.ceil(s.player.hp)} / ${s.player.maxHp} HEALTH`:u.id==='ammo'?'ALL OWNED WEAPONS':`${u.id==='grenade'?s.grenades:s.inventory[u.id]} IN STOCK`}</span><button class="primary" data-action="buy" data-kind="supply" data-id="${u.id}" ${full||s.cash<u.price?'disabled':''}>${full?'FULL':`${fmt(u.price)} CR · BUY`}</button></div></article>`;}).join('');
  dialog('shop','The armory.',s.wave?`BEFORE WAVE ${s.wave+1}`:'BEFORE WAVE 1',`${`<nav class="shop-tabs" aria-label="Armory categories">${['weapons','defenses','upgrades','supplies'].map(t=>`<button data-action="tab" data-id="${t}" class="${shopTab===t?'active':''}">${t.toUpperCase()}</button>`).join('')}</nav>`}<div class="dialog-body"><div class="shop-grid">${cards}</div></div>`,`<span>Exit to walk around and place defenses.<br>Only Start wave begins combat. Purchases autosave.</span><button class="primary" data-action="prepare">Exit shop · Prepare →</button>`,true,`<div class="bank">${fmt(s.cash)} <small>CR</small></div>`);hud();}
function returnToPrep(){if(game?.prepare()){persist();resume();hud();notice('Prepare your defenses. Start the next wave when you are ready.');}}
function openArmory(){if(game?.openShop()){shopTab='defenses';showShop();}}
function showLoadout(){if(!game||game.s.phase==='dead')return;paused=true;resetInput();persist();if(!game)return;const s=game.s;dialog('loadout','Field loadout.','ON THE FLY',`<div class="dialog-body"><h3>Main weapon</h3><div class="shop-grid">${s.owned.map(id=>`<article class="shop-card"><div class="shop-art">${gunSvg(id)}</div><div class="shop-card-body"><h3>${GUN[id].name}</h3><span class="chip">${GUN[id].ammo<0?'UNLIMITED AMMO':`${s.ammo[id]} ROUNDS`}</span><button class="${s.weapon===id?'owned':'primary'}" data-action="equip" data-id="${id}" ${s.weapon===id?'disabled':''}>${s.weapon===id?'ACTIVE':'EQUIP'}</button></div></article>`).join('')}</div><h3>Deployable gear</h3><div class="shop-grid">${BUILD_TYPES.map(id=>`<article class="shop-card"><div class="shop-art">${gearSvg(id)}</div><div class="shop-card-body"><h3>${id==='wall'?'Structure wall':id[0].toUpperCase()+id.slice(1)}</h3><p>${SUPPLIES.find(v=>v.id===id)?.description||''}</p><span class="chip">${s.inventory[id]} IN STOCK</span><button class="${s.build===id?'owned':'primary'}" data-action="chooseBuild" data-id="${id}" ${s.build===id?'disabled':''}>${s.build===id?'ACTIVE':'SELECT'}</button></div></article>`).join('')}</div></div>`,`<span>Quick swap without leaving the run.</span><button class="primary" data-action="close">${s.phase==='prep'?'Back to preparation':'Back to fight'}</button>`,true);}
function showSettings(){dialog('settings','Your setup.','SETTINGS',`<div class="dialog-body">${[['sound','Sound effects','Synthesized gunfire, hits, and explosions.'],['blood','Blood marks','Cartoon stains remain on the arena floor.'],['shake','Screen shake','Small camera kicks for gunfire and explosions.'],['quality','Effects detail','Low detail lowers render resolution and disables dynamic shadows.']].map(([id,title,desc])=>`<div class="setting-row"><div><strong>${title}</strong><small>${desc}</small></div><button class="${settings[id]===true||settings[id]==='high'?'on':''}" data-action="setting" data-id="${id}" aria-pressed="${settings[id]===true||settings[id]==='high'}">${id==='quality'?settings[id].toUpperCase():settings[id]?'ON':'OFF'}</button></div>`).join('')}</div>`,`<a href="./update.html">Check for game update</a><button class="primary" data-action="close">Done</button>`);}
function showHelp(){dialog('help','Field manual.','STAY ALIVE',`<div class="dialog-body"><p>Survive each wave, buy better equipment, and see how far one life takes you. New games and death clear the single run save.</p><div class="manual-row"><kbd>MOVE</kbd><div><strong>Left stick or WASD / arrows</strong>Circle the horde. Dash with » or Shift when a gap closes.</div></div><div class="manual-row"><kbd>FIRE</kbd><div><strong>Right stick or mouse aim + click</strong>You aim and fire manually. Space also fires. There is no auto-fire.</div></div><div class="manual-row"><kbd>ARSENAL</kbd><div><strong>Tap your main gun, press M, press 1–8, or use Q / E</strong>The pistol never runs out. Ammo crates refill every owned weapon.</div></div><div class="manual-row"><kbd>G / B / M</kbd><div><strong>Grenade / place defense / open loadout</strong>Throw or build in the direction you face. Barrels explode when shot. Mines trigger on enemies. Turrets have limited ammo. Barricades take damage.</div></div><div class="manual-row"><kbd>PICKUPS</kbd><div><strong>Supplies now drop in the arena</strong>Grab ammo, health, frags, and deployables as they hit the floor.</div></div><div class="manual-row"><kbd>PREP</kbd><div><strong>Shop → Exit shop → Prepare → Start wave</strong>Walk around with no time limit. Use More to choose barrels or structure walls, aim, and tap the deploy button. The outline shows the placement. Barrels and walls snap into continuous lines. Reopen the shop any time during prep. Your gun cannot fire until combat begins.</div></div><div class="manual-row"><kbd>CHAIN</kbd><div><strong>Keep kills less than 3.5 seconds apart</strong>Long chains multiply score. Reach 10, 25, 50, or 100 for credits. The 25 and 50 rewards also improve your weapons for this run.</div></div><div class="manual-row"><kbd>CAUTION</kbd><div><strong>Your own explosions can hurt you</strong>Walls stop shots and blasts. Red devil enemies throw fireballs. A warden arrives every fifth wave.</div></div><div class="manual-row"><kbd>SAVE</kbd><div><strong>Pause, close, and continue later</strong>Autosave runs every second and when you pause or switch apps. Reopening does not advance time. Storage is local, not cloud-synced. Clearing website data removes the save.</div></div></div>`,`<button class="primary" data-action="close">Understood</button>`);}
function showInstall(){dialog('install','Keep it on your Home Screen.','IPHONE WEB APP',`<div class="dialog-body"><p>Open this game in <strong>Safari</strong>. Tap <strong>Share</strong>, choose <strong>Add to Home Screen</strong>, leave <strong>Open as Web App</strong> enabled when offered, and tap <strong>Add</strong>.</p><p>Launch it from the new icon. Turn your phone sideways for a wider view. Gameplay is landscape-only. If the browser does not allow an orientation lock, the game pauses behind a rotate prompt instead of shrinking.</p><h3>Install before starting a long run.</h3><p>Safari and the installed app may use separate storage. A save does not automatically move between them, phones, or browsers. Use the same Home Screen app for your run.</p><h3>Offline play</h3><p>Load the game online once and wait for <strong>OFFLINE READY</strong> at the bottom of the menu. The game files are then cached. Browser or system cleanup can still remove cached files and saves.</p></div>`,`<button class="primary" data-action="close">Done</button>`);}
function showAbout(){dialog('about','An old-school last stand.','DEADBLOCK / v'+VERSION,`<div class="dialog-body"><p>An original single-player survival game inspired by the feel of Sean Cooper's Boxhead: More Rooms and Boxhead: The Zombie Wars.</p><p>Game logic, models, layouts, and synthesized audio are original. The real 3D renderer uses Three.js r180 under its MIT license. This is not an official Boxhead release, a Flash port, or a copy of its original assets.</p><p>Seven arenas, including a one-ended runway. Eight firearms. Six upgrade tracks. Explosive barrels, mines, barricades, turrets, and grenades. One automatically saved run.</p><p>No account, ads, analytics, or external runtime downloads.</p><p><a href="https://www.crazymonkeygames.com/series/Boxhead-Series.php" target="_blank" rel="noopener">Read about the original Boxhead series ↗</a></p></div>`,`<button class="primary" data-action="close">Back</button>`);}
function showDeath(){if(!game||deadHandled)return;deadHandled=true;paused=true;resetInput();const s=game.s;store.clear(s.id);store.record(s.score,s.wave,s.kills);warning();$('controls').hidden=true;dialog('death','End of the line.','RUN LOST',`<div class="dialog-body"><p>The horde got through. Your run save has been cleared. Your record stays.</p><div class="stat-grid">${[['SCORE',fmt(s.score)],['WAVE',s.wave],['KILLS',fmt(s.kills)],['BEST CHAIN','×'+s.bestCombo]].map(([label,val])=>`<div class="stat"><small>${label}</small><strong>${val}</strong></div>`).join('')}</div><p>${clock(s.elapsed)} survived in ${MAPS.find(m=>m.id===s.map).name}.</p></div>`,`<button data-action="menu">Main menu</button><button class="primary" data-action="new">New game →</button>`);}
function handleClose(){if(panelKind==='loadout'){persist();resume();return;}if(panelKind==='shop'){returnToPrep();return;}if(panelKind==='pause'){resume();return;}if(panelKind==='death'){toMenu(false);return;}if(panelKind==='new'){if(configReturn==='pause'&&game&&game.s.phase!=='dead')showPause();else toMenu(false);return;}if(panelKind==='confirm'){showNew();return;}if(returnPanel==='pause'&&game&&game.s.phase!=='dead')showPause();else closeDialog();}
function processEvents(){if(!game)return;for(const e of game.drain()){renderer.event(e);audio.event(e);if(e.type==='notice'||e.type==='milestone')notice(e.text);if(e.type==='clear'){store.record(game.s.score,game.s.wave,game.s.kills);showShop();}if(e.type==='death')showDeath();}if(game?.s.phase==='dead')showDeath();}
function movement(){const raw={mx:clamp(move.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),-1,1),my:clamp(move.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),-1,1)};const v=renderer.screenVectorToWorld(raw.mx,raw.my);return {mx:v.x,my:v.y};}
function currentInput(){const {mx,my}=movement(),manual=Math.hypot(aim.x,aim.y)>.18;let angle=null;if(manual){const v=renderer.screenVectorToWorld(aim.x,aim.y);angle=Math.atan2(v.y,v.x);}else if(mouse.valid){const w=renderer.screenToWorld(mouse.x,mouse.y);angle=Math.atan2(w.y-game.s.player.y,w.x-game.s.player.x);}return{mx,my,aim:angle,fire:manual||mouse.down||keys.has(' '),auto:false};}
function hud(){if(!game)return;const s=game.s,p=s.player,prep=s.phase==='prep';$('prepBar').hidden=!prep||s.phase==='dead';const startLabel=`Start wave ${s.wave+1} →`;if($('startWaveButton').textContent!==startLabel)$('startWaveButton').textContent=startLabel;document.querySelector('#aimStick .stick-ring span').textContent=prep?'AIM / BUILD':'AIM / FIRE';const set=(id,val)=>{if($(id).textContent!==String(val))$(id).textContent=val;};set('healthNumber',`${Math.ceil(p.hp)} / ${p.maxHp}`);$('healthBar').firstElementChild.style.width=(p.hp/p.maxHp*100)+'%';$('healthBar').firstElementChild.style.background=p.hp/p.maxHp<.3?'#e59d72':'#d4e982';$('healthBar').setAttribute('aria-valuenow',String(Math.ceil(p.hp)));$('healthBar').setAttribute('aria-valuemax',String(p.maxHp));set('arenaName',MAPS.find(m=>m.id===s.map).name.toUpperCase());set('waveNumber',String(s.wave).padStart(2,'0'));set('enemyNumber',prep?'PREPARATION':`${s.enemies.length+s.remaining} HOSTILES`);set('scoreNumber',String(Math.floor(s.score)).padStart(6,'0'));set('cashNumber',fmt(s.cash)+' CR');$('comboReadout').style.opacity=!prep&&s.combo>1?'1':'0';set('comboNumber',`×${s.combo} CHAIN`);$('comboFill').style.width=(s.comboTime/3.5*100)+'%';set('dashLabel',p.dash>0?`DASH ${p.dash.toFixed(1)}`:'DASH');set('grenadeLabel',`FRAG · ${s.grenades}`);set('placeLabel',`${s.build.toUpperCase()} · ${s.inventory[s.build]}`);$('dashButton').disabled=p.dash>0;$('grenadeButton').disabled=prep||s.grenades===0;$('placeButton').disabled=s.inventory[s.build]===0;const active=s.weapon,dockKey=active+':'+s.owned.join(',');if(lastDock!==dockKey){lastDock=dockKey;$('weaponDock').innerHTML=`<button class="weapon-slot active main" data-action="loadout" data-id="${active}" aria-label="Current weapon: ${GUN[active].name}. Open loadout" aria-pressed="true"><span class="key">${WEAPONS.findIndex(w=>w.id===active)+1}</span>${gunSvg(active)}<span class="weapon-name">${GUN[active].short}</span><span class="ammo">${GUN[active].ammo<0?'∞':s.ammo[active]}</span></button><button class="weapon-slot more-slot" data-action="loadout" aria-label="Open loadout"><span class="key">M</span><span class="action-symbol">⋯</span><span class="weapon-name">MORE</span><span class="ammo">${s.owned.length} GUNS</span></button>`;}document.querySelector('#weaponDock .main .ammo').textContent=GUN[active].ammo<0?'∞':s.ammo[active];}
async function act(action,id,kind){if(action==='landscape'){requestLandscape();return;}if(rotationBlocked)return;if(['begin','start','continue','next'].includes(action))requestLandscape();audio.unlock();switch(action){case'continue':resumeSaved();break;case'new':configReturn=game&&game.s.phase!=='dead'?'pause':'menu';if(game&&game.s.phase!=='dead'){paused=true;persist();}showNew();break;case'map':selectedMap=id;showNew();break;case'difficulty':selectedDifficulty=id;showNew();break;case'begin':confirmNew();break;case'start':startNew();break;case'backNew':showNew();break;case'pause':showPause();break;case'resume':resume();break;case'menu':toMenu();break;case'close':handleClose();break;case'prepare':returnToPrep();break;case'shop':openArmory();break;case'next':if(game?.nextWave()){persist();resume();hud();processEvents();}break;case'tab':shopTab=id;showShop();break;case'buy':if(game?.buy(kind,id)){persist();processEvents();showShop();}break;case'equip':if(game){game.equip(id);if(game.s.phase==='shop'){persist();showShop();}else if(panelKind==='loadout'){showLoadout();}hud();}break;case'loadout':if(game)showLoadout();break;case'chooseBuild':if(game&&BUILD_TYPES.includes(id)){game.s.build=id;hud();if(panelKind==='loadout')showLoadout();notice(`${id.toUpperCase()} selected.`);}break;case'settings':returnPanel=game&&game.s.phase!=='dead'?'pause':'menu';if(game)paused=true;showSettings();break;case'help':returnPanel=game&&game.s.phase!=='dead'?'pause':'menu';if(game)paused=true;showHelp();break;case'install':returnPanel='menu';showInstall();break;case'about':returnPanel='menu';showAbout();break;case'setting':settings[id]=id==='quality'?(settings.quality==='high'?'low':'high'):!settings[id];store.settings(settings);audio.unlock();showSettings();hud();break;case'dash':if(game&&!paused){const m=movement();game.dash(m.mx,m.my);processEvents();}break;case'grenade':if(game&&!paused){game.grenade();processEvents();}break;case'place':if(game&&!paused){game.place();processEvents();}break;}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;act(b.dataset.action,b.dataset.id,b.dataset.kind).catch(err=>{console.error(err);notice('An error occurred. Your last saved run is still available.');});});
$('panel').addEventListener('cancel',e=>{e.preventDefault();handleClose();});
function stick(id,obj){const el=$(id);const update=e=>{const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,n=Math.hypot(dx,dy),k=n>45?45/n:1;obj.x=dx*k/45;obj.y=dy*k/45;el.style.setProperty('--dx',dx*k+'px');el.style.setProperty('--dy',dy*k+'px');};el.addEventListener('pointerdown',e=>{if(paused||!game||obj.id!==null)return;e.preventDefault();obj.id=e.pointerId;el.setPointerCapture(e.pointerId);update(e);audio.unlock();});el.addEventListener('pointermove',e=>{if(obj.id===e.pointerId){e.preventDefault();update(e);}});const end=e=>{if(obj.id!==e.pointerId)return;obj.id=null;obj.x=obj.y=0;el.style.setProperty('--dx','0px');el.style.setProperty('--dy','0px');};for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,end);}
stick('moveStick',move);stick('aimStick',aim);
$('gameCanvas').addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||paused)return;mouse.x=e.clientX;mouse.y=e.clientY;mouse.valid=true;});
$('gameCanvas').addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||paused||e.button!==0)return;mouse.x=e.clientX;mouse.y=e.clientY;mouse.valid=true;mouse.down=true;$('gameCanvas').setPointerCapture(e.pointerId);audio.unlock();});
for(const type of ['pointerup','pointercancel','lostpointercapture'])$('gameCanvas').addEventListener(type,()=>mouse.down=false);
$('gameCanvas').addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='escape'||k==='p'){if(!$('panel').open&&game){e.preventDefault();showPause();}return;}if(!game||paused||rotationBlocked||$('panel').open)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','shift','q','e','g','b','m'].includes(k)||/^[1-8]$/.test(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='shift')act('dash');if(k==='g')act('grenade');if(k==='b')act('place');if(k==='m')act('loadout');if(k==='q'||k==='e'){game.cycle(k==='q'?-1:1);hud();}if(/^[1-8]$/.test(k)){game.equip(WEAPONS[Number(k)-1].id);hud();}});
window.addEventListener('keyup',e=>{if(game&&!paused&&!$('panel').open&&e.key===' ')e.preventDefault();keys.delete(e.key.toLowerCase());});
function suspend(){resetInput();if(game&&game.s.phase!=='dead'){paused=true;persist();if(game&&panelKind!=='shop')showPause();}last=performance.now();acc=0;}
document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();else{last=performance.now();acc=0;}});
window.addEventListener('pagehide',suspend);window.addEventListener('blur',()=>{setTimeout(()=>{if(game&&!paused&&(document.hidden||!document.hasFocus()))suspend();},80);});
window.addEventListener('storage',e=>{if(e.key===SAVE_KEY&&game){const r=store.read();if(!r||r.owner!==store.owner)conflict();}else if(e.key===SAVE_KEY)refreshMenu();});
window.addEventListener('resize',scheduleViewport);window.visualViewport?.addEventListener('resize',scheduleViewport);window.addEventListener('orientationchange',scheduleViewport);screen.orientation?.addEventListener('change',scheduleViewport);$('orientationGate').addEventListener('cancel',e=>e.preventDefault());
function frame(now){const dt=Math.min(.08,Math.max(0,(now-last)/1000));last=now;if(game&&!paused&&!rotationBlocked&&!renderer.lost&&!document.hidden){acc+=dt;let steps=0;while(acc>=1/60&&steps++<5&&game&&!paused){game.tick(1/60,currentInput());acc-=1/60;processEvents();}saveClock+=dt;if(saveClock>=1){saveClock=0;persist();}}else acc=0;hudClock+=dt;if(hudClock>.09){hudClock=0;hud();}const shown=game||attract;renderer.placement=game?.s.phase==='prep'?game.previewPlacement():null;if(!rotationBlocked)renderer.draw(shown.s,shown.map,game&&paused?0:dt,!game);requestAnimationFrame(frame);}
window.addEventListener('deadblockgraphicslost',()=>{suspend();notice('Graphics interrupted. Your run is paused and saved.');});
window.addEventListener('deadblockgraphicsrestored',()=>{notice('Graphics restored. Tap Resume when ready.');});
refreshMenu();updateViewport();requestLandscape();$('boot').remove();requestAnimationFrame(frame);
if('serviceWorker'in navigator&&!new URLSearchParams(location.search).has('test')){
  navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(async reg=>{await navigator.serviceWorker.ready;$('offlineStatus').textContent='OFFLINE READY / v'+VERSION;reg.update().catch(()=>{});}).catch(()=>{$('offlineStatus').textContent='ONLINE PLAY / v'+VERSION;});
}
// Test hooks exist only on a local test server, never on GitHub Pages.
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('test'))window.__deadblock={get game(){return game;},get paused(){return paused;},store,enter,startNew,persist,showShop,processEvents,toMenu,currentInput,renderer,showLoadout,resume,returnToPrep,openArmory,updateViewport,get rotationBlocked(){return rotationBlocked;}};
